### ISSUE TITLE
能否添加Bark的消息群组，谢谢

### ISSUE THREAD

**Issue by hanlihanshaobo** [zzsj0928/luci-app-pushbot#21]

**Comment by zzsj0928** [comment]
不好意思由于跟随  tty228/luci-app-serverchan 主项目的进度，目前对于Bark的支持已暂停。
（其使用了新的架构，非常的便捷）
我会考虑尽量不带来过多变更的情况下支持GET模式的推送（Bark用的GET，而目前统一使用POST json）

**Comment by zzsj0928** [comment]
现已支持（刚更新的3.55-3版本起支持）
