### ISSUE TITLE
建议添加新推送项目

### ISSUE THREAD

**Issue by ghost** [zzsj0928/luci-app-pushbot#26]
能不能添加推送web登录，ssh登录推送，登录失败类推送，这样能实时了解路由器情况，防止外部入侵暴力破解……

**Comment by hnrrn** [comment]
哈哈哈。我倒是想了解一下你的使用环境 。。。

**Comment by zzsj0928** [comment]
跟随主项目 tty228/luci-app-serverchan 更新
抄过来了这个功能，目前已经支持了
