### ISSUE TITLE
钉钉推送 能否支持 加签的安全设置。

### ISSUE THREAD

**Issue by 82kg** [zzsj0928/luci-app-pushbot#38]
钉钉的推送机器人有  三个来源限制， 
1、自定义关键字
2、加签
3、来源IP

现在用的自定义关键字，设置的路由器名称。 pushbot 推送的消息里不带路由名称的消息就无法推送了

来源IP 对家宽不适用，动态IP会变。

请问作者能否支持下  加签。这样安全也方便。

**Comment by xylz0928** [comment]
路由器名称会默认添加在推送内容的标题里。
所以关键字用路由器名称即可。
加签是更安全但对于路由器状态推送没必要。

**Comment by 82kg** [comment]
好的 谢谢回复
