### ISSUE TITLE
推送模式的下拉菜单里面少了Telegram选项，请添加

### ISSUE THREAD

**Issue by VPN-V2Ray** [zzsj0928/luci-app-pushbot#40]
推送模式的下拉菜单里面少了Telegram选项，请添加Telegram选项，这个太常用了。

**Comment by smtp268** [comment]
如何在 推送模式的下拉菜单里面 加Telegram选项 ？？非常需要在pushbot里面添加这个Telegram推送。原server酱是有的，但希望 pushbot能也添加Telegram推送的选项。
