### ISSUE TITLE
希望 pushbot也能添加Telegram推送的选项。

### ISSUE THREAD

**Issue by VPN-V2Ray** [zzsj0928/luci-app-pushbot#42]
如何在 推送模式的下拉菜单里面 加Telegram选项 ？？
原server酱是有的，但希望 pushbot也能添加Telegram推送的选项。
非常需要在pushbot里面添加这个Telegram推送。

**Comment by zzsj0928** [comment]
serverchan本身支持

**Comment by VPN-V2Ray** [comment]
> serverchan本身支持

serverchan本身支持, 
 希望pushbot也增加对Telegram的支持啊。
 在代码里如何增加对Telegram的支持？？

**Comment by VPN-V2Ray** [comment]
> 自己加，要么安装luci-app-serverchan，很简单的，改下luci的文件就好了。

 在Pushbot的代码里 如何增加对Telegram的支持？？
