### ISSUE TITLE
飞书推送不成功

### ISSUE THREAD

**Issue by limboking** [zzsj0928/luci-app-pushbot#56]
已经添加了飞书自定义机器人的webhook，但测试发送没有收到消息，日志里显示已经推送成功

**Comment by panda62** [comment]
![image](https://user-images.githubusercontent.com/40233059/162961083-a145b7c3-6642-482e-a61e-0a38cb80ada5.png)
作者在模板里面是这样匹配的，所以我们只需要填hook地址的后面半截，这个看作者愿不愿加个说明吧，确实是个坑，找了好久的原因，估计是因为我没用过这个东西吧
