### ISSUE TITLE
自动拉黑无效

### ISSUE THREAD

**Issue by HalcyonDaysssss** [zzsj0928/luci-app-pushbot#95]
当登录openwrt失败一定次数，或者ssh登录失败一定次数，不会拉黑ip

**Comment by wangyw6716** [comment]
ssh登录失败, 自动拉黑ip可参考一下方法自行修改

![image](https://github.com/zzsj0928/luci-app-pushbot/assets/59910348/2e908c92-763f-4aa8-a096-fb5fefaae96f)

1. 通过logread命令或者UI界面查看系统日志, 找到SSH 错误尝试输出的日志
2. 将带有ip那条日志, 固定不变的部分复制下来粘贴到上图中双引号之中, 重启服务后生效

脚本对应的路径:
```
vim /usr/bin/pushbot/pushbot
```
例如我的N1是这样的
![image](https://github.com/zzsj0928/luci-app-pushbot/assets/59910348/a9c45df1-1839-4333-98f2-6edf1f8f7159)
我就将Failed password for root from替换图一选中部分, 不同的系统可能不一样
